# Generated by Django 4.1.5 on 2023-02-07 19:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('post', models.CharField(max_length=50)),
                ('position', models.SmallIntegerField(unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'is_visible'),
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(unique=True, upload_to=main_page.models.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='text',
        ),
        migrations.RemoveField(
            model_name='event',
            name='position',
        ),
        migrations.AddField(
            model_name='about',
            name='header',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='header_strong',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='about',
            name='position',
            field=models.SmallIntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.FileField(blank=True, upload_to=main_page.models.get_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dishes', to='main_page.category'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='position',
            field=models.SmallIntegerField(unique=True),
        ),
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', models.CharField(max_length=800)),
                ('position', models.SmallIntegerField(db_index=True, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_paragraphs', to='main_page.about')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='AboutList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_line', models.CharField(max_length=300)),
                ('position', models.SmallIntegerField(db_index=True, unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_lists', to='main_page.about')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
    ]
