# Generated by Django 4.1.5 on 2023-02-07 20:20

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_chef_galleryphoto_remove_about_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.get_file_name),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='position',
            field=models.SmallIntegerField(),
        ),
    ]
