# Generated by Django 4.1.5 on 2023-02-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_alter_chef_photo_alter_whyus_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='About us', max_length=50),
        ),
    ]
