# Generated by Django 4.1.5 on 2023-02-08 14:17

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_about_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chef',
            old_name='post',
            new_name='specialty',
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(default='About us', max_length=50),
        ),
        migrations.AlterField(
            model_name='chef',
            name='position',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.get_file_name),
        ),
    ]
