# Generated by Django 4.1.5 on 2023-02-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_rename_post_chef_specialty_galleryphoto_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(db_index=True, max_length=50, unique=True)),
                ('occupation', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=300)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('is_visible',),
            },
        ),
    ]
