# Generated by Django 4.1.5 on 2023-02-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='booking_time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
