# Generated by Django 4.1.5 on 2023-02-15 17:54

import ckeditor.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0013_remove_aboutparagraph_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', ckeditor.fields.RichTextField(blank=True)),
                ('open_hours', ckeditor.fields.RichTextField(blank=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('email', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Error email', regex='(\\w+[-_.]?\\w+)+@(\\w+.)+[A-Za-z]+')])),
                ('subject', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=1000)),
                ('date_incoming', models.DateTimeField(auto_now_add=True)),
                ('viewed', models.BooleanField(default=False)),
            ],
        ),
    ]
